### ISSUE TITLE
Config flow could not be loaded: 500 Internal Server Error

### ISSUE THREAD

**Issue by PersistentDabbler** [Anrolosia/Shopping-List-with-Grocy#16]
I am getting this error when trying to add the integration. The message "Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble" comes up instead of starting the configuration. Grocy is the addon version. 

```This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/shopping_list_with_grocy/config_flow.py:134
Integration: Shopping List with Grocy (documentation, issues)
First occurred: 10:46:19 AM (1 occurrences)
Last logged: 10:46:19 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 67, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 234, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 148, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 831, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 859, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/shopping_list_with_grocy/config_flow.py", line 134, in async_step_user
    cv.int, vol.In([0, 100, 200, 400])
AttributeError: module 'homeassistant.helpers.config_validation' has no attribute 'int'
```

**Comment by Anrolosia** [comment]
Oh damned, thanks @PersistentDabbler for this, I'll push a fix asap!

**Comment by PersistentDabbler** [comment]
Looks like it's still not happy.

```This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/shopping_list_with_grocy/config_flow.py:135
Integration: Shopping List with Grocy (documentation, issues)
First occurred: 11:06:11 AM (2 occurrences)
Last logged: 11:06:50 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 67, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 234, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 148, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 831, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 859, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/shopping_list_with_grocy/config_flow.py", line 135, in async_step_user
    default=self.options.get("image_download_size", 0),
AttributeError: 'ShoppingListWithGrocyConfigFlow' object has no attribute 'options'
```

**Comment by Anrolosia** [comment]
Is this a new installation or you used the plugin before? Let me take a look, that's strange...

**Comment by rachaelbond** [comment]
@Anrolosia The upgrade has just worked for me :)

**Comment by Anrolosia** [comment]
@PersistentDabbler New update pushed (v0.5.2), please give it a try :)

**Comment by PersistentDabbler** [comment]
Working now! You're awesome!! Thank you!!
